name: "Curl it out"
on: push

jobs:
  curl-run:
    runs-on: ubuntu-latest
    steps:
      - name: install curl
        run: apt-get install curl
      - name: check request
        run:  curl -i -u prio101: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 https://api.github.com/users/prio101 