name: "Curl it out"
on: push

jobs:
  curl-run:
    runs-on: ubuntu-latest
    steps:
      - name: install curl
        run:  sudo apt-get install curl
      - name: check request
        run:  curl -i -u prio101:$token https://api.github.com/users/prio101 